module.exports = {
  dock: 'modules/desk/wm/dock',
  litechat_message: 'window/litechat/message',
  notifier_generic: 'desk/notifier/generic',
  notifier_network: 'desk/notifier/network',
  schedule_invitation: 'window/schedule/widget/invitation',
  schedule_recipient: 'window/schedule/widget/recipient',
  selection: 'window/selection',
  user: 'desk/user',
  window_account: 'window/account',
  window_addressbook: 'window/addressbook',
  window_bigchat: 'window/bigchat',
  window_server_explorer: 'window/serverexplorer',
  window_channel: 'window/channel',
  window_choice: 'window/choice',
  window_confirm: 'window/confirm',
  window_connect: 'window/connect',
  window_contact: 'window/contact',
  window_downloader: 'window/downloader',
  window_filter: 'window/filter',
  window_folder: 'window/folder',
  window_helpdesk: 'window/helpdesk',
  window_info: 'window/info',
  window_launcher: 'window/launcher',
  // window_litechat: 'window/litechat', TO DO
  window_manager: 'desk/wm/index.electron',
  window_meeting: 'window/meeting',
  window_schedule: 'window/schedule',
  window_search: 'window/search',
  window_sharebox: 'window/sharebox',
  window_supportticket: 'window/supportticket',
  window_switchcall: 'window/switchcall',
  window_team: 'window/team',
  window_trash: 'window/trash',
  window_website: 'window/website',
};
