const members = [
  {
    id: "u1",
    initials: "JV",
    avatar_color: "purple",
    name: "Julian Vance",
    email: "julian.v@drumee.io",
    role: { label: "organization name owner", variant: "owner" },
    workspaces: [{ label: "Drumee" }],
    status: "online",
    last_active: "Just now",
  },
  {
    id: "u2",
    initials: "SC",
    avatar_color: "amber",
    name: "Sarah Chen",
    email: "s.chen@drumee.io",
    role: { label: "Workspace Admin", variant: "admin" },
    workspaces: [
      { label: "Techteam" },
      { label: "marketing team" },
    ],
    status: "online",
    last_active: "14 mins ago",
  },
  {
    id: "u3",
    initials: "AM",
    avatar_color: "cyan",
    name: "Alex Martinez",
    email: "alex.m@external.com",
    role: { label: "Member", variant: "member" },
    workspaces: [{ label: "marketing team" }],
    status: "away",
    last_active: "3 hours ago",
  },
  {
    id: "u4",
    initials: "LF",
    avatar_color: "pink",
    name: "Liam Foster",
    email: "l.foster@drumee.io",
    role: { label: "Member", variant: "member" },
    workspaces: [{ label: "tech team" }],
    status: "online",
    last_active: "2 mins ago",
  },
  {
    id: "u5",
    initials: "JV",
    avatar_color: "purple",
    name: "Julian Vance",
    email: "julian.v@drumee.io",
    role: { label: "Workspace Admin", variant: "admin" },
    workspaces: [{ label: "Drumee" }],
    status: "online",
    last_active: "Just now",
  },
  {
    id: "u6",
    initials: "SC",
    avatar_color: "amber",
    name: "Sarah Chen",
    email: "s.chen@drumee.io",
    role: { label: "Workspace Admin", variant: "admin" },
    workspaces: [{ label: "marketing team" }],
    status: "online",
    last_active: "14 mins ago",
  },
  {
    id: "u7",
    initials: "AM",
    avatar_color: "cyan",
    name: "Alex Martinez",
    email: "alex.m@external.com",
    role: { label: "Member", variant: "member" },
    workspaces: [
      { label: "tech team" },
      { label: "launch" },
    ],
    status: "away",
    last_active: "3 hours ago",
  },
];

export default members;
