const storageUsers = [
  {
    id: "s1",
    initials: "EV",
    avatar_color: "dark",
    name: "Elena Vance",
    email: "elena.v@drumee.io",
    role: { label: "Admin", variant: "admin" },
    percent: 82,
    bar_color: "high",
    storage: "842 GB",
  },
  {
    id: "s2",
    initials: "MT",
    avatar_color: "dark",
    name: "Marcus Thorne",
    email: "m.thorne@drumee.io",
    role: { label: "Admin", variant: "admin" },
    percent: 45,
    bar_color: "mid",
    storage: "460 GB",
  },
  {
    id: "s3",
    initials: "SK",
    avatar_color: "cyan",
    name: "Sarah Kovach",
    email: "sarah.k@drumee.io",
    role: { label: "Member", variant: "member" },
    percent: 12,
    bar_color: "low",
    storage: "124 GB",
  },
  {
    id: "s4",
    initials: "EV",
    avatar_color: "dark",
    name: "Elena Vance",
    email: "elena.v@drumee.io",
    role: { label: "Admin", variant: "admin" },
    percent: 82,
    bar_color: "high",
    storage: "842 GB",
  },
  {
    id: "s5",
    initials: "MT",
    avatar_color: "dark",
    name: "Marcus Thorne",
    email: "m.thorne@drumee.io",
    role: { label: "Admin", variant: "admin" },
    percent: 45,
    bar_color: "mid",
    storage: "460 GB",
  },
];

export default storageUsers;
