module.exports = {
  acknowledge: '__ack__',
  addTag: 'add-tag',
  allContacts: 'all-contacts',
  data: {
    direction: 'data-direction',
    drag: 'data-drag',
    error: 'data-error',
    flow: 'data-flow',
    from: 'data-from',
    hide: 'data-hide',
    iconPosition: 'data-icon--position',
    node: 'data-node',
    over: 'data-over',
    position: 'data-position',
    pseudo: 'data-pseudo',
    radio: 'data-radio',
    radiotoggle: 'data-radiotoggle',
    role: 'data-role',
    row: 'data-row',
    selected: 'data-selected',
    size: 'data-size',
    split: 'data-split',
    state: 'data-state',
    status: 'data-status',
    title: 'data-title',
    toggle: 'data-toggle',
  },
  nid: 'nid',
  no_cache: 'no-cache',
  no_icon: 'no-icon',
  no_label: 'no_label',
  no_text: 'no-text',
  nodeId: 'nid',
  noLink: 'no-link',
  parentId: 'pid',
  templateName: 'template',
};

