// Generated by CoffeeScript 1.12.7
(function() {
  var __leaflet,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  __leaflet = (function(superClass) {
    extend(__leaflet, superClass);

    function __leaflet() {
      this.onStart = bind(this.onStart, this);
      return __leaflet.__super__.constructor.apply(this, arguments);
    }

    __leaflet.prototype.onStart = function() {
      var circle, marker, mymap, polygon;
      this.debug("STARTINGonStart");
      mymap = L.map(this._id).setView([51.505, -0.09], 13);
      L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw', {
        maxZoom: 18,
        attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
        id: 'mapbox.streets'
      }).addTo(mymap);
      marker = L.marker([51.5, -0.09]).addTo(mymap);
      circle = L.circle([51.508, -0.11], {
        color: 'red',
        fillColor: '#f03',
        fillOpacity: 0.5,
        radius: 500
      }).addTo(mymap);
      return polygon = L.polygon([[51.509, -0.08], [51.503, -0.06], [51.51, -0.047]]).addTo(mymap);
    };

    return __leaflet;

  })(Letc.snippet);

  module.exports = __leaflet;

}).call(this);
