module.exports = {
  account_avatar: 'window/account/profile/avatar',
  account_country: 'window/account/widget/country',
  account_data: 'window/account/data',
  account_input: 'window/account/widget/input',
  account_privacy: 'window/account/privacy',
  account_preferences: 'window/account/preferences',
  account_profile: 'window/account/profile',
  account_security: 'window/account/security',
  account_subscription: 'window/account/subscription',
  account_apps: 'window/account/apps',
  otp_sms: 'window/account/security/otp/sms',
  otp_email: 'window/account/security/otp/email',
  otp_passkey: 'window/account/security/otp/passkey',
  privacy_switcher: 'window/account/privacy/switcher',
  security_email: 'window/account/security/email',
  security_pass: 'window/account/security/pass',
  security_phone: 'window/account/security/phone',
  security_ident: 'window/account/security/ident',
  security_ip: 'window/account/security/ip',
  security_otp: 'window/account/security/otp',
  security_switcher: 'window/account/security/switcher',
};
