module.exports = {
  address_input_item: './address-input-item/index',
  contact_invitation_form: './contact-invitation-form',
  disk_usage: './disk-usage',
  email_input_item: './email-input-item/index',
  phoneno_input_item: './phoneno-input-item/index',
  widget_chat: './chat',
  settings_folder: './settings/folder',
  settings_hub: './settings/hub',
  settings_members_list: './settings/members-list',
  settings_helpcenter: './settings/helpcenter',
  settings_member: './settings/member',
  settings_account: './settings/account',
  settings_pricing: './settings/pricing',
  settings_filename: './settings/filename',
  widget_chat_item: './chat-item',
};