module.exports = {
  address_input_item: './address-input-item/index',
  contact_invitation_form: './contact-invitation-form',
  disk_usage: './disk-usage',
  email_input_item: './email-input-item/index',
  phoneno_input_item: './phoneno-input-item/index',
  widget_chat: './chat',
  settings_account: './settings/account',
  settings_activity_hub_item: './settings/activity-hub/item',
  settings_activity_hub: './settings/activity-hub',
  settings_billing: './settings/account/billing',
  settings_filename: './settings/filename',
  settings_folder: './settings/folder',
  settings_helpcenter: './settings/helpcenter',
  settings_hub: './settings/hub',
  settings_member: './settings/member',
  settings_members_list: './settings/members-list',
  // settings_pricing: './settings/pricing',
  settings_share_hub: './settings/share-hub',
  settings_access_manager: './settings/access-manager',
  // settings_share_hub_custom: './settings/share-hub-custom',
  settings_private_hub: './settings/private-hub',
  widget_chat_item: './chat-item',
};