//==================================================================== *
//  Copyright Xialia.com  2011-2018
//  FILE : ../src/drumee/libs/type/class/reader
//  TYPE :
//==================================================================== *

// Lazy Classes cannot be overloaded
__seeds_classes = {
  avatar: 'libs/reader/avatar',
  button_anchor: 'libs/reader/ui/button/anchor',
  button_blank: 'libs/reader/ui/button/blank',
  button_icon: 'libs/reader/button',
  button_nested: 'libs/reader/ui/button/nested',
  button_rotate: 'libs/reader/ui/button/rotate',
  button_switch: 'libs/reader/ui/button/switch',
  button_switcher: 'libs/reader/ui/button/switcher',
  button_toggle: 'libs/reader/ui/button/toggle',
  button_trigger: 'libs/reader/ui/button/trigger',
  button: 'libs/reader/ui/button',
  chart_bar: 'libs/reader/chart/bar',
  chart_line: 'libs/reader/chart/line',
  chart_pie: 'libs/reader/chart/pie',
  chart_sline: 'libs/reader/chart/sline',
  chart_time_series: 'libs/reader/chart/time-series',
  editor_json: 'editor/json',
  entry_input: 'libs/reader/entry/input',
  entry_reminder: 'libs/reader/entry/reminder',
  entry_search: 'libs/reader/entry/search',
  entry_text: 'libs/reader/entry/text',
  entry: 'libs/reader/entry/input',
  fileselector: 'libs/reader/file-selector',
  form: 'libs/reader/form',
  image_smart: 'libs/reader/image/smart',
  image_svg: 'libs/reader/image/svg',
  list_smart: 'libs/reader/list/smart',
  list_table: 'libs/reader/list/table',
  list_table_row: 'libs/reader/list/table/row',
  menubox: 'libs/reader/menu',
  menu_topic: 'libs/reader/menu',
  menu_wrapper: 'libs/reader/menu',
  messenger: 'libs/reader/messenger',
  profile: 'libs/reader/profile',
  progress: 'libs/reader/progress/media',
  progress_bar: 'libs/reader/progress/bar',
  rich_text: 'libs/reader/text/editable',
  search: 'libs/reader/entry/search',
  slidebar: 'libs/reader/slidebar',
  slidebar_input: 'libs/reader/slidebar-input/slidebar-input',
  svg: 'libs/reader/image/svg',
  svg_circle_percent: 'libs/reader/svg/circle-percent',
  svg_gradient_circle: 'libs/reader/svg/gradient-circle',
  svg_line: 'libs/reader/svg/line',
  svg_path: 'libs/reader/svg/path',
};
module.exports = __seeds_classes
